In [251]:
import numpy as np

## Task 1-a
All the angles printed are in degrees.
### Task 1-a-Stanford

In [252]:
l1=0.25
l2=0.25
m1=0.8
m2=0.8
m3=0.8
I1=0.005
I2=0.005
I3=0.8

In [253]:
def Stanford_invkin(x,y,z):
    q1=np.arctan2(y,x)
    r=np.sqrt(x**2+y**2)
    s=z-l1
    q2=np.arctan2(s,r)
    d3=np.sqrt(s**2+r**2)-l2
    
    jp=np.array([np.rad2deg(q1),np.rad2deg(q2),d3])
    print("-->Joint parameters:", jp)
    return q1,q2,d3

In [254]:
def Stanford_fkin(q1,q2,d3):
    n=3
#     the wrong DH parameters that works!
#     dh=np.array([[q1, l1, 0, np.pi/2],
#                  [q2, 0, l2, 0],
#                  [0, 0, d3, 0]])

    dh=np.array([[q1, l1, 0, np.pi/2],
                 [np.pi/2+q2, 0, 0, np.pi/2],
                 [0, l2+d3, 0, 0]])
    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    pos=ans[0:3,3]
    print("   Position of end effector:", pos)
    return pos

In [255]:
#point A
q1,q2,d3=Stanford_invkin(0.45,0.075,0.1)
pos=Stanford_fkin(q1,q2,d3)
#point B
q1,q2,d3=Stanford_invkin(0.45,-0.075,0.1)
pos=Stanford_fkin(q1,q2,d3)
#point C
q1,q2,d3=Stanford_invkin(0.25,-0.075,0.1)
pos=Stanford_fkin(q1,q2,d3)
#point D
q1,q2,d3=Stanford_invkin(0.25,0.075,0.1)
pos=Stanford_fkin(q1,q2,d3)

-->Joint parameters: [  9.46232221 -18.20076026   0.23023432]
   Position of end effector: [0.45  0.075 0.1  ]
-->Joint parameters: [ -9.46232221 -18.20076026   0.23023432]
   Position of end effector: [ 0.45  -0.075  0.1  ]
-->Joint parameters: [-16.69924423 -29.88580023   0.05103986]
   Position of end effector: [ 0.25  -0.075  0.1  ]
-->Joint parameters: [ 16.69924423 -29.88580023   0.05103986]
   Position of end effector: [0.25  0.075 0.1  ]


### Task 1-a-PUMA

In [256]:
l1=0.25
l2=0.25
l3=0.25
m1=0.8
m2=0.8
m3=0.8
I1=0.005
I2=0.005
I3=0.8

In [257]:
def PUMA_invkin(x,y,z):
    q1=np.arctan2(y,x)
    r=np.sqrt(x**2+y**2)
    s=z-l1
    
    D=(r**2+s**2-l2**2-l3**2)/(2*l2*l3)
    q3=-np.arctan2(np.sqrt(1-D**2),D)  # negative because we want the end effector to have downwards orientation
    q2=np.arctan2(s,r)-np.arctan2(l3*np.sin(q3),l2+l3*np.cos(q3))
    
    jp=np.array([np.rad2deg(q1),np.rad2deg(q2),np.rad2deg(q3)])
    print("-->Joint parameters:", jp)
    return q1,q2,q3

In [258]:
def PUMA_fkin(q1,q2,q3):
    n=3
    dh=np.array([[q1, l1, 0, np.pi/2],
                 [q2, 0, l2, 0],
                 [q3, 0, l3, 0]])

    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    pos=ans[0:3,3]
    print("   Position of end effector:", pos)
    return pos

In [259]:
#point A
q1,q2,q3=PUMA_invkin(0.45,0.075,0.1)
pos=PUMA_fkin(q1,q2,q3)
#point B
q1,q2,q3=PUMA_invkin(0.45,-0.075,0.1)
pos=PUMA_fkin(q1,q2,q3)
#point C
q1,q2,q3=PUMA_invkin(0.25,-0.075,0.1)
pos=PUMA_fkin(q1,q2,q3)
#point D
q1,q2,q3=PUMA_invkin(0.25,0.075,0.1)
pos=PUMA_fkin(q1,q2,q3)

-->Joint parameters: [  9.46232221  -2.0367282  -32.32806412]
   Position of end effector: [0.45  0.075 0.1  ]
-->Joint parameters: [ -9.46232221  -2.0367282  -32.32806412]
   Position of end effector: [ 0.45  -0.075  0.1  ]
-->Joint parameters: [ -16.69924423   23.09520685 -105.96201416]
   Position of end effector: [ 0.25  -0.075  0.1  ]
-->Joint parameters: [  16.69924423   23.09520685 -105.96201416]
   Position of end effector: [0.25  0.075 0.1  ]


### Task 1-a-SCARA

In [260]:
l1=0.25
l2=0.25
l3=0.25
m1=0.8
m2=0.8
m3=0.8
I1=0.005
I2=0.005
I3=0.8

In [261]:
def SCARA_invkin(x,y,z):
    D=(x**2+y**2-l2**2-l3**2)/(2*l2*l3)
    q2=np.arctan2(np.sqrt(1-D**2),D)
    q1=np.arctan2(y,x)-np.arctan2(l3*np.sin(q2),l2+l3*np.cos(q2))
    
    d3=z-l1
    
    jp=np.array([np.rad2deg(q1),np.rad2deg(q2),d3])
    print("-->Joint parameters:", jp)
    return q1,q2,d3

In [262]:
def SCARA_fkin(q1,q2,q3):
    n=3
    dh=np.array([[q1, l1, l2, 0],
                 [q2, 0, l2, 0],
                 [0, d3, 0, 0]])

    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    pos=ans[0:3,3]
    print("   Position of end effector:", pos)
    return pos

In [263]:
#point A
q1,q2,d3=SCARA_invkin(0.45,0.075,0.1)
pos=SCARA_fkin(q1,q2,d3)
#point B
q1,q2,d3=SCARA_invkin(0.45,-0.075,0.1)
pos=SCARA_fkin(q1,q2,d3)
#point C
q1,q2,d3=SCARA_invkin(0.25,-0.075,0.1)
pos=SCARA_fkin(q1,q2,d3)
#point D
q1,q2,d3=SCARA_invkin(0.25,0.075,0.1)
pos=SCARA_fkin(q1,q2,d3)

-->Joint parameters: [-14.6965151   48.31767461  -0.15      ]
   Position of end effector: [0.45  0.075 0.1  ]
-->Joint parameters: [-33.62115951  48.31767461  -0.15      ]
   Position of end effector: [ 0.45  -0.075  0.1  ]
-->Joint parameters: [-75.23171135 117.06493423  -0.15      ]
   Position of end effector: [ 0.25  -0.075  0.1  ]
-->Joint parameters: [-41.83322288 117.06493423  -0.15      ]
   Position of end effector: [0.25  0.075 0.1  ]


## Task 1-b

In [264]:
points=[0]*4
for i in range(4):
    points[i]=[float(i) for i in input("Enter x{} and y{}: ".format(i+1,i+1)).split()]

Enter x1 and y1: 0.1 0.2
Enter x2 and y2: 0.2 0.2
Enter x3 and y3: 0.2 0.1
Enter x4 and y4: 0.1 0.1


In [265]:
print("For Stanford-type")
for i in range(4):
    q1,q2,d3=Stanford_invkin(points[i][0],points[i][1],0.1)
    pos=Stanford_fkin(q1,q2,d3)
print()
print("For PUMA-type")
for i in range(4):
    q1,q2,q3=PUMA_invkin(points[i][0],points[i][1],0.1)
    pos=PUMA_fkin(q1,q2,q3)
print()
print("For SCARA-type")
for i in range(4):
    q1,q2,d3=SCARA_invkin(points[i][0],points[i][1],0.1)
    pos=SCARA_fkin(q1,q2,d3)

For Stanford-type
-->Joint parameters: [ 6.34349488e+01 -3.38545148e+01  1.92582404e-02]
   Position of end effector: [0.1 0.2 0.1]
-->Joint parameters: [ 45.         -27.93835273   0.07015621]
   Position of end effector: [0.2 0.2 0.1]
-->Joint parameters: [ 2.65650512e+01 -3.38545148e+01  1.92582404e-02]
   Position of end effector: [0.2 0.1 0.1]
-->Joint parameters: [ 4.50000000e+01 -4.66861433e+01 -4.38447187e-02]
   Position of end effector: [0.1 0.1 0.1]

For PUMA-type
-->Joint parameters: [  63.43494882   23.56277893 -114.83458749]
   Position of end effector: [0.1 0.2 0.1]
-->Joint parameters: [  45.           22.24652717 -100.36975981]
   Position of end effector: [0.2 0.2 0.1]
-->Joint parameters: [  26.56505118   23.56277893 -114.83458749]
   Position of end effector: [0.2 0.1 0.1]
-->Joint parameters: [  45.           18.96379305 -131.29987279]
   Position of end effector: [0.1 0.1 0.1]

For SCARA-type
-->Joint parameters: [  0.         126.86989765  -0.15      ]
   Positio

## Task 1-c

In [266]:
points=[[0.4, 0.06], [0.4, 0.01], [0.35, 0.01], [0.35, 0.06]]

print("For Stanford-type")
for i in range(4):
    q1,q2,d3=Stanford_invkin(points[i][0],points[i][1],0.1)
    pos=Stanford_fkin(q1,q2,d3)
print()
print("For PUMA-type")
for i in range(4):
    q1,q2,q3=PUMA_invkin(points[i][0],points[i][1],0.1)
    pos=PUMA_fkin(q1,q2,q3)
print()
print("For SCARA-type")
for i in range(4):
    q1,q2,d3=SCARA_invkin(points[i][0],points[i][1],0.1)
    pos=SCARA_fkin(q1,q2,d3)

For Stanford-type
-->Joint parameters: [  8.53076561 -20.34735591   0.18139309]
   Position of end effector: [0.4  0.06 0.1 ]
-->Joint parameters: [  1.43209618 -20.5501612    0.17731721]
   Position of end effector: [0.4  0.01 0.1 ]
-->Joint parameters: [  1.63657704 -23.1901278    0.13091994]
   Position of end effector: [0.35 0.01 0.1 ]
-->Joint parameters: [  9.72757855 -22.89965963   0.13548671]
   Position of end effector: [0.35 0.06 0.1 ]

For PUMA-type
-->Joint parameters: [  8.53076561  10.02177432 -60.73826047]
   Position of end effector: [0.4  0.06 0.1 ]
-->Joint parameters: [  1.43209618  10.73046775 -62.5612579 ]
   Position of end effector: [0.4  0.01 0.1 ]
-->Joint parameters: [  1.63657704  17.18320514 -80.74666588]
   Position of end effector: [0.35 0.01 0.1 ]
-->Joint parameters: [  9.72757855  16.65895944 -79.11723814]
   Position of end effector: [0.35 0.06 0.1 ]

For SCARA-type
-->Joint parameters: [-27.47577049  72.0130722   -0.15      ]
   Position of end effect

## Task 1-d

In [267]:
def dh_2_jacobian_v(dh,n,R_or_P):
    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)
    Z=[0]*(n+1)
    Z[0]=np.array([[0],
                   [0],
                   [1]])
    O=[0]*(n+1)
    O[0]=np.array([0, 0, 0])
    for i in range(n):
        ans=ans@A[i]
        Z[i+1]=ans[0:3, 0:3]@Z[0]
        O[i+1]=ans[0:3,3].T
    
    print("   position of end effector:", ans[0:3,3])
    
    J=[0]*n
    for i in range(n):
        if R_or_P[i]==1:
            J[i]=np.concatenate((Z[i],np.array([[0,0,0]]).T),axis=0)
        else:
            cross=np.cross(Z[i].T,(O[n]-O[i]).T)
            J[i]=np.concatenate((cross.T,Z[i]),axis=0)

    final_J=J[0]
    for i in range(1,n):
        final_J=np.concatenate((final_J,J[i]),axis=1)
    # jacobian matrix done
    Jv=final_J[0:3]
    return Jv

In [268]:
def Stanford_1d(x,y,z,vx,vy,vz):
    q1,q2,d3=Stanford_invkin(x,y,z) # prints joint parameters as well
    
    n=3
    dh=np.array([[q1, l1, 0, np.pi/2],
                 [np.pi/2+q2, 0, 0, np.pi/2],
                 [0, l2+d3, 0, 0]])
    R_or_P=[0,0,1]

    Jv=dh_2_jacobian_v(dh,n,R_or_P)
    v=np.array([[vx],
                [vy],
                [vz]])
    join_velocities=np.linalg.pinv(Jv)@v
    print("   velocity of end effector:", v.T)
    print("   velocity of joint variables:", join_velocities.T)
    
def PUMA_1d(x,y,z,vx,vy,vz):
    q1,q2,q3=PUMA_invkin(x,y,z) # prints joint parameters as well
    
    n=3
    dh=np.array([[q1, l1, 0, np.pi/2],
                 [q2, 0, l2, 0],
                 [q3, 0, l3, 0]])
    R_or_P=[0,0,0]

    Jv=dh_2_jacobian_v(dh,n,R_or_P)
    v=np.array([[vx],
                [vy],
                [vz]])
    join_velocities=np.linalg.pinv(Jv)@v
    print("   velocity of end effector:", v.T)
    print("   velocity of joint variables:", join_velocities.T)
    
def SCARA_1d(x,y,z,vx,vy,vz):
    q1,q2,d3=SCARA_invkin(x,y,z) # prints joint parameters as well
    
    # finding jacobian matrix
    n=3
    dh=np.array([[q1, l1, l2, 0],
                 [q2, 0, l2, 0],
                 [0, d3, 0, 0]])
    R_or_P=[0,0,1]

    Jv=dh_2_jacobian_v(dh,n,R_or_P)
    v=np.array([[vx],
                [vy],
                [vz]])
    join_velocities=np.linalg.pinv(Jv)@v
    print("   velocity of end effector:", v.T)
    print("   velocity of joint variables:", join_velocities.T)

In [269]:
points=[[0.4, 0.06], [0.4, 0.01], [0.35, 0.01], [0.35, 0.06]]

print("For Stanford-type")
print("from A to B")
for i in range(4):
    Stanford_1d(points[0][0],points[0][1]-(i+1)/100,0.1, 0,-0.01,0)
print("from B to C")
for i in range(4):
    Stanford_1d(points[1][0]-(i+1)/100,points[1][1],0.1, -0.01,0,0)
print("from C to D")
for i in range(4):
    Stanford_1d(points[2][0],points[2][1]+(i+1)/100,0.1, 0,0.01,0)
print("from D to A")
for i in range(4):
    Stanford_1d(points[3][0]+(i+1)/100,points[3][1],0.1, 0.01,0,0)
print()
print()
print("For PUMA-type")
print("from A to B")
for i in range(4):
    PUMA_1d(points[0][0],points[0][1]-(i+1)/100,0.1, 0,-0.01,0)
print("from B to C")
for i in range(4):
    PUMA_1d(points[1][0]-(i+1)/100,points[1][1],0.1, -0.01,0,0)
print("from C to D")
for i in range(4):
    PUMA_1d(points[2][0],points[2][1]+(i+1)/100,0.1, 0,0.01,0)
print("from D to A")
for i in range(4):
    PUMA_1d(points[3][0]+(i+1)/100,points[3][1],0.1, 0.01,0,0)
print()
print()
print("For SCARA-type")
print("from A to B")
for i in range(4):
    SCARA_1d(points[0][0],points[0][1]-(i+1)/100,0.1, 0,-0.01,0)
print("from B to C")
for i in range(4):
    SCARA_1d(points[1][0]-(i+1)/100,points[1][1],0.1, -0.01,0,0)
print("from C to D")
for i in range(4):
    SCARA_1d(points[2][0],points[2][1]+(i+1)/100,0.1, 0,0.01,0)
print("from D to A")
for i in range(4):
    SCARA_1d(points[3][0]+(i+1)/100,points[3][1],0.1, 0.01,0,0)

For Stanford-type
from A to B
-->Joint parameters: [  7.12501635 -20.41044552   0.18011626]
   position of end effector: [0.4  0.05 0.1 ]
   velocity of end effector: [[ 0.   -0.01  0.  ]]
   velocity of joint variables: [[-0.02461538 -0.00100569 -0.00116248]]
-->Joint parameters: [  5.71059314 -20.46250378   0.17906876]
   position of end effector: [0.4  0.04 0.1 ]
   velocity of end effector: [[ 0.   -0.01  0.  ]]
   velocity of joint variables: [[-0.02475248 -0.00081073 -0.00093225]]
-->Joint parameters: [  4.28915333 -20.5032705    0.17825226]
   position of end effector: [0.4  0.03 0.1 ]
   velocity of end effector: [[ 0.   -0.01  0.  ]]
   velocity of joint variables: [[-0.02486016 -0.0006117  -0.00070052]]
-->Joint parameters: [  2.86240523 -20.53253945   0.1776681 ]
   position of end effector: [0.4  0.02 0.1 ]
   velocity of end effector: [[ 0.   -0.01  0.  ]]
   velocity of joint variables: [[-0.02493766 -0.00040955 -0.00046765]]
from B to C
-->Joint parameters: [  1.46880071

## Task 1-e

In [270]:
l1=0.25
l2=0.25
l3=0.25
m1=0.8
m2=0.8
m3=0.8
I1=0.005
I2=0.005
I3=0.8

d6=0.05
R=np.array([[1, 0, 0],
            [0, -1, 0],
            [0, 0, -1]])

In [271]:
def Stanford_invkin_wrist_1e(ox,oy,oz):
    x=ox-d6*R[0][2]
    y=oy-d6*R[1][2]
    z=oz-d6*R[2][2]
    
    q1,q2,d3=Stanford_invkin(x,y,z)
    return q1,q2,d3
def Stanford_fkin_wrist_1e(q1,q2,d3):
    pos=Stanford_fkin(q1,q2,d3)
    
    pos[0]+=d6*R[0][2]
    pos[1]+=d6*R[1][2]
    pos[2]+=d6*R[2][2]
    print("   Position of end effector after adding wrist:", pos)
    return pos

def PUMA_invkin_wrist_1e(ox,oy,oz):
    x=ox-d6*R[0][2]
    y=oy-d6*R[1][2]
    z=oz-d6*R[2][2]
    
    q1,q2,q3=PUMA_invkin(x,y,z)
    return q1,q2,q3
def PUMA_fkin_wrist_1e(q1,q2,q3):
    pos=PUMA_fkin(q1,q2,q3)
    
    pos[0]+=d6*R[0][2]
    pos[1]+=d6*R[1][2]
    pos[2]+=d6*R[2][2]
    print("   Position of end effector after adding wrist:", pos)
    return pos

def SCARA_invkin_wrist_1e(ox,oy,oz):
    x=ox-d6*R[0][2]
    y=oy-d6*R[1][2]
    z=oz-d6*R[2][2]
    
    q1,q2,d3=SCARA_invkin(x,y,z)
    return q1,q2,d3
def SCARA_fkin_wrist_1e(q1,q2,d3):
    pos=SCARA_fkin(q1,q2,d3)
    
    pos[0]+=d6*R[0][2]
    pos[1]+=d6*R[1][2]
    pos[2]+=d6*R[2][2]
    print("   Position of end effector after adding wrist:", pos)
    return pos

In [272]:
points=[[0.4, 0.06], [0.4, 0.01], [0.35, 0.01], [0.35, 0.06]]

print("For Stanford-type")
for i in range(4):
    q1,q2,d3=Stanford_invkin_wrist_1e(points[i][0],points[i][1],0.1)
    pos=Stanford_fkin_wrist_1e(q1,q2,d3)
print()
print("For PUMA-type")
for i in range(4):
    q1,q2,q3=PUMA_invkin_wrist_1e(points[i][0],points[i][1],0.1)
    pos=PUMA_fkin_wrist_1e(q1,q2,q3)
print()
print("For SCARA-type")
for i in range(4):
    q1,q2,d3=SCARA_invkin_wrist_1e(points[i][0],points[i][1],0.1)
    pos=SCARA_fkin_wrist_1e(q1,q2,d3)

For Stanford-type
-->Joint parameters: [  8.53076561 -13.88699366   0.16665333]
   Position of end effector: [0.4  0.06 0.15]
   Position of end effector after adding wrist: [0.4  0.06 0.1 ]
-->Joint parameters: [  1.43209618 -14.03203244   0.16243181]
   Position of end effector: [0.4  0.01 0.15]
   Position of end effector after adding wrist: [0.4  0.01 0.1 ]
-->Joint parameters: [  1.63657704 -15.93922205   0.11414283]
   Position of end effector: [0.35 0.01 0.15]
   Position of end effector after adding wrist: [0.35 0.01 0.1 ]
-->Joint parameters: [  9.72757855 -15.72755722   0.11891733]
   Position of end effector: [0.35 0.06 0.15]
   Position of end effector after adding wrist: [0.35 0.06 0.1 ]

For PUMA-type
-->Joint parameters: [  8.53076561  19.67308009 -67.12014752]
   Position of end effector: [0.4  0.06 0.15]
   Position of end effector after adding wrist: [0.4  0.06 0.1 ]
-->Joint parameters: [  1.43209618  20.39330012 -68.85066511]
   Position of end effector: [0.4  0.01 

### Task 1-f

In [273]:
def Euler_angles(R,show=1):
    if not(R[0][2]==0 and R[1][2]==0):
        q2=np.arctan2(np.sqrt(1-R[2][2]**2), R[2][2])
        q3=np.arctan2(R[2][1], -R[2][0])
        q1=np.arctan2(R[1][2], R[0][2])
    elif R[2][2]==1:
        q2=0
        q1=0
        q3=np.arctan2(R[1][0], R[0][0])
    elif R[2][2]==-1:
        q2=np.pi
        q1=0
        q3=np.arctan2(R[1][0], -R[0][0])
    else:
        print("something is wrong")
    if(show):
        print("   Euler angles:",np.around(np.rad2deg(q1),5),np.around(np.rad2deg(q2),5),np.around(np.rad2deg(q3),5))
    return q1,q2,q3

def Euler_matrix(q1,q2,q3):
    r1=np.array([[np.cos(q1), -np.sin(q1), 0],
                 [np.sin(q1), np.cos(q1), 0],
                 [0, 0, 1]])
    r2=np.array([[np.cos(q2), 0, np.sin(q2)],
                 [0, 1, 0],
                 [-np.sin(q2), 0, np.cos(q2)]])
    r3=np.array([[np.cos(q3), -np.sin(q3), 0],
                 [np.sin(q3), np.cos(q3), 0],
                 [0, 0, 1]])
    r=r1@r2@r3
    return r

In [274]:
def Stanford_invkin_wrist_1f(ox,oy,oz):
    x=ox-d6*R[0][2]
    y=oy-d6*R[1][2]
    z=oz-d6*R[2][2]
    q1,q2,d3=Stanford_invkin(x,y,z)
    
    # forward kinematics to find R03
    n=3
    dh=np.array([[q1, l1, 0, np.pi/2],
                 [np.pi/2+q2, 0, 0, np.pi/2],
                 [0, l2+d3, 0, 0]])
    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)
    for i in range(n):
        ans=ans@A[i]
    R03=ans[0:3,0:3]
    
    R36=R03.T@R
    
    # finding wrist angles using Euler angles for matrix R36
    q4,q5,q6=Euler_angles(R36)
    
    return q1,q2,d3,q4,q5,q6

def PUMA_invkin_wrist_1f(ox,oy,oz):
    x=ox-d6*R[0][2]
    y=oy-d6*R[1][2]
    z=oz-d6*R[2][2]
    q1,q2,q3=PUMA_invkin(x,y,z)
    
    # forward kinematics to find R03
    n=3
    dh=np.array([[q1, l1, 0, np.pi/2],
                 [q2, 0, l2, 0],
                 [q3, 0, l3, 0]])

    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    R03=ans[0:3,0:3]
    
    R36=R03.T@R
    
    # finding wrist angles using Euler angles for matrix R36
    q4,q5,q6=Euler_angles(R36)
    
    return q1,q2,q3,q4,q5,q6

def SCARA_invkin_wrist_1f(ox,oy,oz):
    x=ox-d6*R[0][2]
    y=oy-d6*R[1][2]
    z=oz-d6*R[2][2]
    q1,q2,d3=SCARA_invkin(x,y,z)
    
    # forward kinematics to find R03
    n=3
    dh=np.array([[q1, l1, l2, 0],
                 [q2, 0, l2, 0],
                 [0, d3, 0, 0]])

    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    R03=ans[0:3,0:3]
    
    R36=R03.T@R
    
    # finding wrist angles using Euler angles for matrix R36
    q4,q5,q6=Euler_angles(R36)
    
    return q1,q2,d3,q4,q5,q6

In [275]:
def Stanford_fkin_wrist_1f(q1,q2,d3,q4,q5,q6):
    n=3
    dh=np.array([[q1, l1, 0, np.pi/2],
                 [np.pi/2+q2, 0, 0, np.pi/2],
                 [0, l2+d3, 0, 0]])
    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    pos=ans[0:3,3]
    R03=ans[0:3,0:3]
    
    R36=Euler_matrix(q4,q5,q6)
    R_final=R03@R36
    
    pos[0]+=d6*R_final[0][2]
    pos[1]+=d6*R_final[1][2]
    pos[2]+=d6*R_final[2][2]
    print("   Position of end effector after adding wrist:", pos)
    print("   orientation of end effector after adding wrist:")
    print(np.around(R_final,5))
    
    return pos

def PUMA_fkin_wrist_1f(q1,q2,q3,q4,q5,q6):
    n=3
    dh=np.array([[q1, l1, 0, np.pi/2],
                 [q2, 0, l2, 0],
                 [q3, 0, l3, 0]])

    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    pos=ans[0:3,3]
    R03=ans[0:3,0:3]
    
    R36=Euler_matrix(q4,q5,q6)
    R_final=R03@R36
    
    pos[0]+=d6*R_final[0][2]
    pos[1]+=d6*R_final[1][2]
    pos[2]+=d6*R_final[2][2]
    print("   Position of end effector after adding wrist:", pos)
    print("   orientation of end effector after adding wrist:")
    print(np.around(R_final,5))
    
    return pos

def SCARA_fkin_wrist_1f(q1,q2,d3,q4,q5,q6):
    n=3
    dh=np.array([[q1, l1, l2, 0],
                 [q2, 0, l2, 0],
                 [0, d3, 0, 0]])

    A=[0]*n
    for i in range(n):
        theta, d, a, alpha = dh[i]
        A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                       [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                       [0, np.sin(alpha), np.cos(alpha), d],
                       [0, 0, 0, 1]])
    ans=np.identity(4)

    for i in range(n):
        ans=ans@A[i]
    pos=ans[0:3,3]
    R03=ans[0:3,0:3]
    
    R36=Euler_matrix(q4,q5,q6)
    R_final=R03@R36
    
    pos[0]+=d6*R_final[0][2]
    pos[1]+=d6*R_final[1][2]
    pos[2]+=d6*R_final[2][2]
    print("   Position of end effector after adding wrist:", pos)
    print("   orientation of end effector after adding wrist:")
    print(np.around(R_final,5))
    
    return pos

In [276]:
points=[[0.4, 0.06], [0.4, 0.01], [0.35, 0.01], [0.35, 0.06]]

print("For Stanford-type")
for i in range(4):
    q1,q2,d3,q4,q5,q6=Stanford_invkin_wrist_1f(points[i][0],points[i][1],0.1)
    pos=Stanford_fkin_wrist_1f(q1,q2,d3,q4,q5,q6)
print()
print()
print("For PUMA-type")
for i in range(4):
    q1,q2,q3,q4,q5,q6=PUMA_invkin_wrist_1f(points[i][0],points[i][1],0.1)
    pos=PUMA_fkin_wrist_1f(q1,q2,q3,q4,q5,q6)
print()
print()
print("For SCARA-type")
for i in range(4):
    q1,q2,d3,q4,q5,q6=SCARA_invkin_wrist_1f(points[i][0],points[i][1],0.1)
    pos=SCARA_fkin_wrist_1f(q1,q2,d3,q4,q5,q6)

For Stanford-type
-->Joint parameters: [  8.53076561 -13.88699366   0.16665333]
   Euler angles: -180.0 76.11301 -171.46923
   Position of end effector after adding wrist: [0.4  0.06 0.1 ]
   orientation of end effector after adding wrist:
[[ 1. -0. -0.]
 [-0. -1.  0.]
 [-0. -0. -1.]]
-->Joint parameters: [  1.43209618 -14.03203244   0.16243181]
   Euler angles: -180.0 75.96797 -178.5679
   Position of end effector after adding wrist: [0.4  0.01 0.1 ]
   orientation of end effector after adding wrist:
[[ 1.  0. -0.]
 [ 0. -1.  0.]
 [ 0. -0. -1.]]
-->Joint parameters: [  1.63657704 -15.93922205   0.11414283]
   Euler angles: -180.0 74.06078 -178.36342
   Position of end effector after adding wrist: [0.35 0.01 0.1 ]
   orientation of end effector after adding wrist:
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [-0. -0. -1.]]
-->Joint parameters: [  9.72757855 -15.72755722   0.11891733]
   Euler angles: -180.0 74.27244 -170.27242
   Position of end effector after adding wrist: [0.35 0.06 0.1 ]
   orien